/obj/secure_closet/kitchen/New()
	..()
	sleep(2)
	new /obj/item/clothing/head/chefhat(src)
	new /obj/item/clothing/head/chefhat(src)
	new /obj/item/clothing/under/rank/chef(src)
	new /obj/item/clothing/under/rank/chef(src)
	new /obj/item/weapon/kitchen/utensil/fork(src)
	new /obj/item/weapon/kitchen/utensil/knife(src)
	new /obj/item/weapon/kitchen/utensil/spoon(src)
	new /obj/item/weapon/kitchen/rollingpin(src)

/obj/secure_closet/meat/New()
	..()
	sleep(2)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/tray(src)
	new /obj/item/weapon/tray(src)
	new /obj/item/weapon/tray(src)
	new /obj/item/weapon/tray(src)
	new /obj/item/weapon/tray(src)
	new /obj/item/weapon/tray(src)
	new /obj/item/kitchen/egg_box(src)
	new /obj/item/kitchen/egg_box(src)
	new /obj/item/weapon/reagent_containers/food/snacks/monkeymeat(src)
	new /obj/item/weapon/reagent_containers/food/snacks/monkeymeat(src)
	new /obj/item/weapon/kitchenknife(src)
	if(prob(95))
		new /obj/item/weapon/reagent_containers/food/snacks/monkeymeat(src)
		new /obj/item/weapon/reagent_containers/food/snacks/monkeymeat(src)
	else
		new /obj/item/weapon/reagent_containers/food/snacks/xenomeat(src)
		new /obj/item/weapon/reagent_containers/food/snacks/xenomeat(src)

/obj/secure_closet/fridge/New()
	..()
	sleep(2)
	new /obj/item/weapon/reagent_containers/food/drinks/milk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/milk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/milk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/milk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/milk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/soymilk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/soymilk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/soymilk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/soymilk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/soymilk(src)

/obj/secure_closet/fridge/fulloffood/New()
	..()
	sleep(2)
	new /obj/item/weapon/reagent_containers/food/drinks/milk(src)
	new /obj/item/weapon/reagent_containers/food/drinks/soymilk(src)
	new /obj/item/weapon/reagent_containers/food/snacks/flour(src)
	new /obj/item/weapon/reagent_containers/food/snacks/donut( src )
	new /obj/item/weapon/reagent_containers/food/snacks/donkpocket( src )
	new /obj/item/weapon/reagent_containers/food/snacks/cheesewheel( src )
	new /obj/item/weapon/reagent_containers/food/snacks/monkeyburger( src )
	new /obj/item/weapon/reagent_containers/food/snacks/fries( src )
	new /obj/item/weapon/reagent_containers/food/snacks/monkeymeat( src )
	new /obj/item/weapon/reagent_containers/food/snacks/faggot( src )
	new /obj/item/weapon/reagent_containers/food/snacks/banana( src )
	new /obj/item/weapon/reagent_containers/food/snacks/pie( src )
	new /obj/item/weapon/reagent_containers/food/snacks/waffles( src )
	new /obj/item/weapon/reagent_containers/food/snacks/jellydonut( src )
	new /obj/item/weapon/reagent_containers/food/snacks/cheesecake( src )
	new /obj/item/weapon/reagent_containers/food/snacks/syndicake( src )
	new /obj/item/weapon/reagent_containers/food/snacks/meatbread( src )